---

- name: "Lookup route url for {{ route }}"
  shell: "oc get route {{ route }} -o jsonpath='{ .spec.host }'"
  register: hostname
  when:
  - route is defined
  - route|trim != ''

- name: "Set default delay time"
  set_fact:
    delay: "{{ delay | default(5) }}"

- name: "Set default number of retries"
  set_fact:
    retries: "{{ retries | default(3) }}"

- name: "Wait for {{ protocol }}://{{ hostname.stdout }} to respond with status: {{ status }}"
  uri:
    url: "{{ protocol }}://{{ hostname.stdout }}"
  register: rc
  until: rc.status|trim|int == status|trim|int
  retries: "{{ retries|int }}"
  delay: "{{ delay|int }}"
  when:
  - hostname.stdout is defined
  - hostname.stdout|trim != ''
  - protocol is defined
  - protocol|trim != ''
  - status is defined
  - status|trim != ''
